services:
  web:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    ports:
      - "8000:8000" # Corrected port mapping to match the Dockerfile (Gunicorn binds to 8000)
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    env_file:
      - ./.env
    volumes:
      - ./static:/app/static
      - ./data:/app/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Corrected path to conf.d for proper inclusion
    depends_on:
      - web
    restart: always # Ensures nginx restarts automatically if it crashes

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    depends_on:
      - web
      - nginx
