services:
  - type: web
    name: podcast-generator
    runtime: python
    buildCommand: |
      pip install pipenv
      pipenv install --deploy --ignore-pipfile
    startCommand: pipenv run gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
